spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jackson:
    default-property-inclusion: non_null

jwt:
  secret: f3bcab78-47f3-4111-933e-e4336846293b
  expiration: 999999